INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('00', 0.0025);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('01', 0.0025);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('02', 0.005);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('10', 0.005);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('11', 0.005);

INSERT
INTO SYS_RESTAPI_USER(USER_NAME, PASSWORD)
-- '1234' BCrypt Encoding -> '$2a$10$VxNTrB7uRCPyeJkd5hRey.V5QfB7SwX5DwDS7AFCnjbpyr1paF7Gu'
VALUES ('restapi', '$2a$10$VxNTrB7uRCPyeJkd5hRey.V5QfB7SwX5DwDS7AFCnjbpyr1paF7Gu');

INSERT
INTO SYS_RESTAPI_AUTHORITY(USER_NAME, ROLE)
VALUES ('restapi', 'USER');