INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('00', 0.0025);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('01', 0.0025);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('02', 0.005);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('10', 0.005);

INSERT 
INTO SYS_CARD_POINT(CARD_FRACTION, APP_PERCENT)
VALUES ('11', 0.005);