CREATE TABLE IF NOT EXISTS SYS_CARD_POINT
(
	CARD_FRACTION VARCHAR2(5), 
	APP_PERCENT NUMBER,
	PRIMARY KEY (CARD_FRACTION)
);

COMMENT ON TABLE SYS_CARD_POINT IS '카드 포인트 적립율';
COMMENT ON COLUMN SYS_CARD_POINT.CARD_FRACTION IS '구분';
COMMENT ON COLUMN SYS_CARD_POINT.APP_PERCENT IS '추가 적립율';

CREATE TABLE SYS_REST_ERROR_LOG
(
	ERR_SQ NUMBER NOT NULL,
	ERR_DT DATE,
	ERR_CD VARCHAR2(4000),
	PRIMARY KEY (ERR_SQ)
);

COMMENT ON TABLE SYS_REST_ERROR_LOG IS 'RESTAPI 에러 로깅';
COMMENT ON COLUMN SYS_REST_ERROR_LOG.ERR_SQ IS '에러 시퀀스번호';
COMMENT ON COLUMN SYS_REST_ERROR_LOG.ERR_DT IS '에러 발생일시';
COMMENT ON COLUMN SYS_REST_ERROR_LOG.ERR_CD IS '에러 코드';

CREATE SEQUENCE SEQ_REST_ERROR;
